version: '3'
services:
  ticketing_node_dev:
    container_name: ticketing_node_dev
    build:
      context: .
      dockerfile: ./node/Dockerfile
    working_dir: /app
    command: node /app/server.js
    volumes:
    - ./../src:/app
    ports:
    - 80:80
    - 443:443
    depends_on:
    - ticketing_mysql_dev
  ticketing_mysql_dev:
    container_name: ticketing_mysql_dev
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
    - 3306:3306
    volumes:
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: h4G7f8OP
      MYSQL_USER: ticketing
      MYSQL_PASSWORD: h4G7f8OP
volumes:
  databasevolume:
