version: "3.7"

services:

#  node:
#    image: romarius75/ballkartenonline:ticketing_node
#    build:
#      context: .
#      dockerfile: ./node/Dockerfile
#    working_dir: /app
#    command: node /app/run.js
#    volumes:
#    - ./../src:/app
#    ports:
#    - 80:80
#    - 443:443
#    depends_on:
#    - ticketing_mysql_name
#    networks:
#      - ticketing

  mysql:
    image: romarius75/ballkartenonline:ticketing_mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
    - 3306:3306
    volumes:
    - ticketing_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: h4G7f8OP
    networks:
      - ticketing

#  ticketing_mssql_dev:
#    container_name: ticketing_mssql_dev
#    build:
#      context: .
#      dockerfile: ./mssql/Dockerfile
#    ports:
#      - 1433:1433
#    volumes:
#      - ticketing_mssql:/var/opt/mssql
#    command: sh -c ' /tmp/entrypoint.sh & /opt/mssql/bin/sqlservr -T7806 --accept-eula;'
#    environment:
#      SA_PASSWORD: ComPle2Pword!
#      ACCEPT_EULA: "Y"
#    networks:
#      - ticketing


volumes:
  ticketing_mysql_volume:
#  ticketing_mssql:

networks:
  ticketing:
    external:
      name: ticketing_nat