version: "3.7"

services:

#  node:
#    image: ticketing_node_dev
#    container_name: ticketing_node_dev_container
#    build:
#      context: .
#      dockerfile: ./node/Dockerfile
#    ports:
#    - 80:80
#    - 443:443
#    volumes:
#    - ./../src:/app
#    depends_on:
#    - mysql
#    networks:
#      - ticketing

  mysql:
    image: ticketing_mysql_dev
    container_name: ticketing_mysql_dev_container
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
    - 3306:3306
    volumes:
    - ticketing_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: h4G7f8OP
    networks:
      - ticketing

volumes:
  ticketing_mysql_volume:

networks:
  ticketing:
    external:
      name: ticketing_nat